import React from 'react';
import { Grid } from 'react-bootstrap';

const StorageTermsPage = () => {
  window.Intercom('trackEvent', 'storage-terms-page');
  return (
    <Grid>
      <h1>StowEdge Storage Terms</h1>
      <h4>TERMS OF SERVICE</h4>
      <p>Last Updated Oct. 25, 2016</p>
      <h4>1. Agreement to Terms Of Service</h4>
      <p>It is agreed that Company’s Terms of Service shall govern the dealings between you and Company for all Services, including, without limitation, Company’s Software and the Storage Service. It is furthermore agreed that Company’s Terms of Service are electronically published at the Site, and may be amended by Company from time to time, without notice. It is expressly understood that these Terms of Service do not cover or apply to any rights, obligations, terms or conditions of the freight forwarding, customs brokerage or other services that Company has provided or may provide to you; and that those separate services shall be governed by their respective Terms of Service which are provided separately and are posted on the above referenced website.</p>
      <p>YOU ACKNOWLEDGE AND AGREE THAT, BY CLICKING ON THE “I AGREE” OR “I ACCEPT” BUTTON OR ACCESSING OR USING THE SERVICES, YOU ARE INDICATING THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE, WHETHER OR NOT YOU HAVE REGISTERED WITH COMPANY. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, THEN YOU HAVE NO RIGHT TO ACCESS OR USE THE SERVICES. BY USING THE SERVICES, YOU CONSENT TO THE COLLECTION, USE AND SHARING OF YOUR INFORMATION IN ACCORDANCE WITH COMPANY’S PRIVACY POLICY.</p>
      <h4>2. Definitions</h4>
      <p>As used in these Terms of Service:</p>
      <p>a. “Company” means the individual or entity listed at the top of these Terms of Service providing the Services hereunder including its officers, directors, employees and agents of the Company while acting within the scope and course of their employment;</p>
      <p>b. “Goods” means the property tendered to Company by you for which Company has agreed to store pursuant to these Terms of Service;</p>
      <p>c. “Services” means all services offered by Company on the Site and otherwise;</p>
      <p>d. “Site” means the internet websites of Company, including the website these Terms of Service are posted on;</p>
      <p>e. “Software” means Company’s logistics software as a service which powers and manages on-demand storage;</p>
      <p>f. “Storage Service” means the pickup, storage and delivery of household items; and</p>
      <p>g. “you” means the person, company, firm or other entity for whom the Goods are stored and to whom these Terms of Service shall apply.</p>
      <h4>3. AGE AND ELIGIBILITY</h4>
      <p>In order to use the Services YOU must be at least 18 years of age or the legal age to form a binding contract in YOUR jurisdiction if that age is greater than 18 years of age. Individuals who are under the age of 18 or the legal age to form a binding contract in their jurisdiction (the "Minors") are prohibited from using the Services. Accordingly, if YOU ARE a Minor, please do not attempt to register for the Services or send any information about YOURSELF to COMPANY, including YOUR name, address, telephone number, or email address. In the event that COMPANY learnS that COMPANY haS collected personal information from a Minor, COMPANY will delete that information as soon as reasonably practicable. If YOU believe that COMPANY might have any information from or about a Minor, please contact us at [____________]. YOU represent that the Registration Data (as defined below) that YOU provide as requested in any account registration form is accurate and complete.</p>
      <h4>4. ACCOUNT REGISTRATION</h4>
      <p>The Services may require you to create an account to participate or to secure additional benefits (the “Account”). You agree to provide, maintain and update true, accurate, current and complete information about yourself as prompted by Company’s registration processes (the "Registration Data"). You also agrees to notify Company promptly at [___________] of any unauthorized use of your username, password, other Account information, or any other breach of security that you become aware of involving or relating to the Services.</p>
      <p>Company may, in Company’s sole and absolute discretion, suspend or terminate your Account and your ability to use the Services or portion thereof for failure to comply with these Terms of Service or any special terms related to a particular service.</p>
      <h4>5. Ownership of Goods</h4>
      <p>You warrant that you are the lawful owner and/or have lawful possession of the Goods tendered for storage. You warrant that you have sole legal rights to store Goods tendered, to release Goods, and to instruct Company regarding pickup, delivery, storage or disposition of the Goods. You agree to notify all parties acquiring any interest in the Goods of the terms and conditions of these Terms of Service and further agree to indemnify and hold Company harmless from any claim by third parties relating to the ownership, storage, handling or delivery of Goods, from any other services provided by Company under these Terms of Service, or from your breach of these Terms of Service. Such indemnification shall include any legal fees or costs incurred from any claim by a third party, regardless of whether or not litigation is actually filed.</p>
      <h4>6. Storage</h4>
      <p>a. Pursuant to the terms and conditions of these Terms of Service, Company agrees to receive, store, and release the Goods in accordance with your reasonable instructions.</p>
      <p>b. If Company determines that the original palletization of Goods must be broken down for storage purposes, Company shall be authorized to break down the pallets without further notice required to you.</p>
      <p>c. Company will store the Goods at its discretion at any one or more buildings at Company’s warehouse location identified on the front side of these Terms of Service. The identification of any specific location with the Company’s warehouse complex does not guarantee that Goods shall be stored therein. Upon [_____ days] prior notice provided to you, Company may at its own expense, remove Goods to any other warehouse complex operated by Company.</p>
      <p>d. Company may provide additional services to you as requested and as agreed. Additional handling charges will apply whenever Goods are pulled for distribution or release, whenever physical inventories are requested by you, and whenever additional services are requested that are not explicitly included in the monthly storage charge quoted to you. Such additional charges will be provided to you and will be invoiced to you in addition to any storage charges due.</p>
      <h4>7. LINKS TO THIRD PARTY SITES, PRODUCTS, AND SERVICES</h4>
      <p>The Services may contain links to third party websites, applications, products, and services that are offered and/or maintained by others (collectively, “Third Party Services”). Any such links are provided solely as a convenience to you and not as an endorsement by Company of the Third Party Services. Company is not responsible for such Third Party Services and does not make any representations or warranties regarding such Third Party Services or the privacy practices of such third parties. If you decide to access such Third Party Services, you do so at your own risk.</p>
      <h4>8. Termination of Storage</h4>
      <p>Company reserves the right to terminate storage and to require the removal of the Goods, or any portion thereof, by giving you [_______ days] advance written notice. You shall be responsible for payment of all charges attributable to said Goods within the stated period and for removing the Goods from the warehouse upon payment of all charges. If the Goods are not so removed, Company may exercise its rights under applicable law including but not limited to selling the Goods.</p>
      <h4>9. YOUR Warranties & Tender for Storage</h4>
      <p>a. You warrant that the Goods are properly marked, packaged, labeled and classified for handling and are fit for storage and any transportation as may be required. Company will not accept Goods that are not properly packaged or which, in the reasonable opinion of Company, are not suitable for movement or storage within the warehouse.</p>
      <p>b. You shall furnish at or prior to delivery, a manifest showing marks, brands or sizes to be accounted for separately and the class of storage desired, if applicable.</p>
      <p>c. Company’s receipt and delivery of a LOT (or partial LOT) shall be made without subsequent sorting except by special arrangement and subject to a charge.</p>
      <p>d. Unless otherwise made known to Company in writing and accepted by Company, you warrant that the Goods are not considered hazardous materials and/or dangerous goods at the time the Goods are tendered to Company. If hazardous materials and/or dangerous goods are tendered for storage and accepted by the Company, a notation shall be so made on the face of these Terms of Service. You warrant that the Goods shall be limited to the permissible materials and quantities in the then current regulations, and agrees to properly classify the Goods, to accurately describe the Goods, and to provide Company with all necessary or useful information for the safe storage and handling of the Goods. If you breach any of the foregoing warranties related to tender of hazardous materials or dangerous goods, or otherwise deliver any such unfit Goods to Company, Company shall be entitled to exercise all available remedies including the immediate destruction or removal of the Goods from the warehouse without notice to you. In the event of the foregoing breach of your warranties, you shall be liable for all expenses costs, losses, damages, fines, penalties or other expenses of any sort incurred by Company in connection with the removal, or destruction, or handling of the Goods and shall indemnify Company against all amounts, liabilities, claims, or damages arising in connection with the Goods.</p>
      <p>e. For all Goods tendered for storage, you shall supply such information and documents as are necessary to comply with all laws, rules and regulations. For all Goods, you shall provide to Company all documents or information necessary or useful for the safe and proper warehousing, handling, storage, and transportation (if any) of the Goods. If all such information and documents are not fully, accurately and timely provided to Company, you shall indemnify Company for all consequences of such failure.</p>
      <p>f. You warrant your compliance with all applicable laws, rules, and regulations including but not limited to customs laws, import and export laws, as well as with the U.S. Foreign Corrupt Practices Act and similar laws related to anti-corruption and anti-bribery.</p>
      <h4>10. Payment Terms & Collection Expenses</h4>
      <p>You shall pay to Company the fees, in the amount and in the manner as set forth on Company’s website, located [___________________].</p>
      <h4>11. Lien Rights</h4>
      <p>Company shall have a lien on the Goods tendered by you and upon any and all property belonging to you in Company’s possession, custody or control for all charges, advances or amounts of any kind due to Company under these Terms of Service or under any prior or subsequent invoices issued to you by Company (including charges for storage, handling, transportation, demurrage, terminal charges, insurance, labor, and any other charges incurred). Company shall have a lien on the Goods and may refuse to surrender possession of the Goods until all charges or debts are paid in full. If such amounts remain unpaid for [____ days] after Company’s demand for payment, Company may sell the Goods at public auction or private sale or in any other manner reasonable, and shall apply the proceeds of such sale to the amounts owed. You remain responsible for any deficiency outstanding to Company.</p>
      <h4>12. WARRANTIES; DISCLAIMERS; LIMITATION ON Liability</h4>
      <p>a. Company shall not be liable for any loss or destruction of or damage to the Goods, however caused, unless such loss, damage or destruction resulted from Company’s failure to exercise such care in regard to the Goods as a reasonably careful person would exercise under like circumstances. Company is not liable for damages which could not have been avoided by the exercise of such care. Company and you mutually agree that Company’s duty of care referred to herein shall not extend to providing a sprinkler system at the warehouse complex or any portion thereof.</p>
      <p>b. In no event shall Company be liable for any loss or damage caused by:</p>
      <p>i. acts of God; public authorities acting with actual or apparent authority; strikes; labor disputes; weather; mechanical or equipment failures; cyber attacks; civil commotions; hazards incident to a state of war; acts of terrorism; acts or omissions of customs or quarantine officials; acts of carriers related to security; the nature of the freight or any defects thereof; inherent vice of the goods; perishable qualities of the merchandise; fires; frost or change of weather; sprinkler leakage; floods; wind; storm; moths; public enemies; or other causes beyond its control;</p>
      <p>ii. fragile articles injured or broken, unless packed by Company’s employees and unpacked by them at the time of delivery;</p>
      <p>iii. pilferage or theft, unless such loss or damage is caused by the failure of Company to exercise such ordinary care required by law; and</p>
      <p>iv. concealed damage, or for losses incurred due to the concealed damage of the Goods.</p>
      <p>c. In the event of loss or damage to the Goods for which Company is legally liable, Company’s liability shall be limited to actual value of the Goods, subject to a maximum of USD $[__] per pound of goods stored, unless you declared a higher value for the goods and Company agrees in writing to purchase insurance for the Goods at your benefit, and you have paid the supplementary charge in accordance with the terms herein.</p>
      <p>d. In no event shall Company be responsible for loss or damage to documents, stamps, securities, artwork, heirlooms, jewelry or other articles of high and unusual value unless a special agreement in writing is made between you and Company with respect to such articles.</p>
      <p>e. THE SERVICES ARE PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, EXCEPT AS SET FORTH BELOW. WITHOUT LIMITING THE FOREGOING, COMPANY EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. COMPANY MAKES NO WARRANTY THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. COMPANY MAKES NO WARRANTY REGARDING THE QUALITY OF ANY PRODUCTS OR SERVICES PURCHASED OR OBTAINED THROUGH THE SERVICES OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY CONTENT OBTAINED THROUGH THE SERVICES.</p>
      <p>f. IN NO EVENT, WHETHER AS A RESULT OF BREACH OF COMPANY’S DUTIES, NEGLIGENCE LIABILITY WITHOUT FAULT OR ANY OTHER LEGAL THEORY OR BASIS, SHALL COMPANY BE LIABLE FOR ANY SPECIAL, INCIDENTAL, CONSEQUENTIAL, STATUTORY OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, LOSS OF PROFITS OR LOSS OF MARKET, LOSS OF INCOME, DAMAGES ARISING FROM LOSS, ATTORNEYS FEES OR PUNITIVE DAMAGES, WRONG DELIVERY, OR DAMAGE TO PROPERTY, LOSS OF USE OF GOODS, COST OF SUBSITUTED GOODS, DELAYED DELIVERY OR FAILURE TO ATTEMPT DELIVERY, WHETHER OR NOT COMPANY HAD KNOWLEDGE THAT SUCH DAMAGES OR LOSSES MIGHT OCCUR.</p>
      <h4>13. Optional Insurance Offering</h4>
      <p>Company does not insure the Goods while in storage and the storage rates or charges billed to you do not include any insurance on the Goods. The Goods will therefore not be insured for any loss or damage, and the limitation of liability set forth in Section 12 shall apply in all circumstances where Company is legally liable for such loss or damage, unless you have requested in writing that Company obtain insurance for the your benefit, and you have paid the required premium to Company for such additional insurance. Except as provided above, Company will not obtain insurance on the Goods for your benefit while the Goods are being stored at Company’s facility.</p>
      <h4>14. Temperature or Humidity Controlled Storage</h4>
      <p>Unless specifically agreed to in writing, Company shall not be responsible for storage of the Goods in a temperature or humidity controlled environment. You knowingly accept that the Goods will be warehoused in a non-temperature/humidity controlled environment. Company will not be responsible for any loss or damage to the Goods that result from fluctuations in temperature range or in humidity levels of the warehouse. Company will furthermore not be responsible for losses or damages incurred to Perishable Goods, unless otherwise agreed to in writing prior to tender of the Goods for storage.</p>
      <h4>15. Inspection & Security</h4>
      <p>All shipments are subject to inspection by Company; by Company’s carriers for any transportation services provided, if any; and by any duly authorized government or regulatory entities, including but not limited to the U.S. Transportation Security Administration, U.S. Customs and Border Protection, and like entities. Notwithstanding the foregoing right to inspect shipments, Company is not obligated to perform such inspection except as mandated by law. Further, Company reserves the right to unilaterally reject any shipment that it deems unfit for transport, or for storage under these Terms of Service, after inspection.</p>
      <h4>16. Notice of Claim and Filing of Suit</h4>
      <p>a. Company shall not be liable for any claim whatsoever for any loss, damage, or destruction of the Goods unless it is timely filed, in writing, within a maximum of [_______ days] after you knew, or should have known by the exercise of reasonable care, of such loss or damage.</p>
      <p>b. Any lawsuit or other claim against Company with respect to the Goods shall be forever waived unless commenced within two (2) years after you knew, or should have known by the exercise of reasonable care, about such loss or damage.</p>
      <h4>17. Notices</h4>
      <p>All written notices herein may be transmitted by any commercially reasonable means of communication providing delivery receipt to the sender, and shall be directed to Company at [________________________] and to you at the address set forth in your Account, unless otherwise instructed by either party in writing.</p>
      <h4>18. Governing Law</h4>
      <p>These Terms of Service shall be governed by the laws of the State where the Company’s warehouse is located, without reference to its conflict of laws principles.</p>
      <h4>19. Merger; Waiver; Severability, etc.</h4>
      <p>These Terms of Service constitutes the entire understanding between you and Company regarding the storage of the Goods and services provided. These Terms of Service supersedes all prior or contemporaneous verbal or written negotiations, statements, representations, or agreements. Company reserves the right, at its sole discretion, to modify, discontinue or terminate the Services or to modify these Terms of Service, at any time and without prior notice. If Company modifies these Terms of Service, Company will post the modification on the Site or provide you with notice of the modification. Company will also update the “Last Updated Date” at the top of these Terms of Service or on the Site. By continuing to access or use the Services after Company has posted a modification on the Site or has provided you with notice of a modification, you are indicating that you agree to be bound by the modified Terms of Service. If the modified Terms of Service are not acceptable to you, your only recourse is to cease using all of the Services.</p>
      <p>If any section or portion of these Terms of Service is held by any court to be illegal or unenforceable it shall not affect the legality or enforceability of the remaining provisions or terms and conditions herein. Company’s failure to insist upon strict compliance with any provision of these Terms of Service shall not constitute a waiver or estoppel to later demand strict compliance thereof and shall not constitute a waiver of or estoppel to insist upon strict compliance with all other provisions of these Terms of Service.</p>
      <h4>20. Headings Not Binding</h4>
      <p>The use of headings in these Terms of Service are for ease of reference only. Headings shall have no effect and are not considered to be part of or a term of these Terms of Service.</p>
    </Grid>
  );
};

export default StorageTermsPage;
