import React from 'react';
import { Grid } from 'react-bootstrap';

const WebsiteTermsPage = () => {
  window.Intercom('trackEvent', 'website-terms-page');
  return (
    <Grid>
      <h1>StowEdge Website Terms</h1>
      <h2>PRIVACY POLICY</h2>
      <p>Last Updated Oct. 25, 2016</p>
      <p>At StowEdge LLC, our most important asset is our relationship with our customer community. We are committed to maintaining the confidentiality, integrity and security of information about our customers. This Privacy Policy describes how we treat personal information when you visit StowEdge LLC’s Site or use our Services.</p>
      <p>This Privacy Policy is incorporated into, and considered a part of, the StowEdge LLC Terms of Service, currently located at [______________]. Any terms not defined herein have the meanings ascribed to them in the Terms of Service.</p>
      <h4>CUSTOMER CONSENT</h4>
      <p>By submitting or making available Personal Data (as defined below) through our Services, the Site, the Software or the Storage Service, you agree to the terms of this Privacy Policy and you expressly consent to the processing of your Personal Data in accordance with this Privacy Policy. Your Personal Data may be processed in the country in which it was collected and in other countries, including the United States, where laws regarding processing of Personal Data may be less stringent than the laws in your country.</p>
      <h4>A NOTE ABOUT CHILDREN</h4>
      <p>We do not intentionally gather Personal Data about visitors who are under the age of 18.</p>
      <h4>TYPES OF PERSONAL DATA WE COLLECT</h4>
      <p>StowEdge LLC collects Personal Data and Anonymous Data (as defined below) from you when you visit our Site, when you send us information or communications in connection with your use of the Services, and/or when you use the Software. “Personal Data” means data that allows someone to identify or contact you, including, for example, your full name, address, along with details regarding the building entrance and access, phone number, geographic location of your computer or mobile device, telephone number, credit/debit card number, email address, bank account information, employer identification numbers, types and quantity of household items stored with us, page history, search term history, or transaction related information, as well as any other non-public information about you that is associated with or linked to any of the foregoing data. “Anonymous Data” means data about you that is not associated with or linked to your Personal Data; Anonymous Data does not permit the identification of individual persons or entities. We collect Personal Data and Anonymous Data, as described below.  We will store data about your purchase history and transaction information, which is stored on a cumulative basis. We will store such information in an aggregate manner that will not be associated with specific customers. We do not respond to browser “do not track” requests. </p>
      <h4>Personal Data You Provide To Us</h4>
      <p>We will collect Personal Data from you, such as first and last name, email and mailing addresses, telephone number, age, and password, when you register and sign up for the Services. In addition, we (or our third-party credit card or payment processor on our behalf) will collect Personal Data including your credit card number or Account information when you register and sign up for the Services. We also retain information on your behalf, such as the Personal Data described above and any correspondence. If you provide us feedback or contact us via email, we will collect your name and email address, IP address, as well as any other content included in the email, in order to send you a reply, and any information that you submit to us. If we conduct a survey in which you participate, we may collect additional profile information. We may also collect Personal Data at other instances on the Site or customer experience where we state that Personal Data is being collected.</p>
      <h4>Personal Data Collected by Third Parties</h4>
      <p>We may receive Personal Data about you from other sources, like telephone or fax, from companies that offer their services via the Services or companies that provide services (such as payment processing services) in connection with the Services (collectively, “Partner Companies”). Our Partner Companies may supply us with Personal Data, such as your name, email, mailing address information, your credit card/debit card or bank information or your login credentials for such Partner Company’s website or service, in order to help us establish the Account or fulfill orders. We may add this information to the information we have already collected from you via our Site in order to perform and improve the Services.</p>
      <p>This Privacy Policy applies only to the use and disclosure of Personal Data that we collect while you use the Services. Our provision of a link to any other website or location is for your convenience and does not signify our endorsement of such other website or location or its contents. The fact that we link to a website or present a banner ad or other type of advertisement is not an endorsement, authorization or representation of our affiliation with that third party, nor is it an endorsement of their privacy or information security policies or practices. We do not exercise control over third party websites. When you click on such a link, you will leave our Site and go to another site. During this process, a third party may collect Personal Data or Anonymous Data from you. We have no control over, do not review, and cannot be responsible for, these outside websites or their content. Please be aware that the terms of this Privacy Policy do not apply to these outside websites or content, or to any collection of data after you click on a link to a third party.</p>
      <h4>Personal Data Collected via Technology</h4>
      <p>The Services (which may be hosted by a third-party service provider) collects Personal Data from you, such as browser type, geographic location of your mobile device or computer, operating system and version, Internet Protocol (IP) address, domain name, information about your application, operating environment and hardware profiles and/or a date/time stamp for your visit. We may also use Cookies (as defined below) and navigational data like Uniform Resource Locators (URL) to gather information regarding the date and time of your visit and/or access to the Services and your activity on the Site. We may also include tracking pixels and web beacons in advertisements or promotions. Like most Internet services, we automatically gather this Personal Data and store it in log files each time you visit the Site, use the Services or access your Account on our network.</p>
      <p>“Cookies” are small pieces of information that a website sends to your computer’s hard drive while you are viewing a web site. We may use both session Cookies (which expire once you close your web browser) and persistent Cookies (which stay on your computer until you delete them, or for an extended period of time) to provide you with a more personal and interactive experience while using the Services. Persistent Cookies can be removed by following Internet browser help file directions. If you choose to disable Cookies, some areas of the Site, the Software and/or the Services may not function correctly.</p>
      <h4>USE OF YOUR PERSONAL DATA</h4>
      <p>StowEdge LLC uses your Personal Data in the following ways:</p>
      <ul>
        <li>to facilitate the creation of and secure your Account on our network;</li>
        <li>to identify you as a customer in our system;</li>
        <li>to manage your Account on our network;</li>
        <li>to provide improved administration of the Services;</li>
        <li>for research and analysis;</li>
        <li>to improve the quality of experience when you interact with the Services;</li>
        <li>to send you a welcome email to verify ownership of the email address provided when your account was created;</li>
        <li>to send you administrative email notifications, such as security or support and maintenance advisories;</li>
        <li>to respond to your inquiries related to employment opportunities or other requests;</li>
        <li>to send promotional communications;</li>
        <li>to provide you with electronic newsletters or surveys;</li>
        <li>to send upgrades and special offers related to the Services and for other marketing purposes of StowEdge LLC or our Partner Companies;</li>
        <li>to make telephone calls to you, from time to time, as a part of secondary fraud protection or to solicit your feedback; and</li>
        <li>to enforce the Terms of Service or this Privacy Policy.</li>
      </ul>
      <p>We may create Anonymous Data records from Personal Data by excluding information (such as your name and email) that render the data personally identifiable to you. We use this Anonymous Data to analyze request and usage patterns so that we may enhance the content and functionality of the Services. StowEdge LLC reserves the right to use for other purposes and to disclose Anonymous Data to third parties in its discretion.</p>
      <p>If you provide feedback on the Services, we may use such feedback for any purpose, provided we will not associate such feedback with your Personal Data. StowEdge LLC will collect and store any information contained in such communication and will treat the Personal Data in such communication in accordance with this Privacy Policy.</p>
      <h4>DISCLOSURE OF YOUR PERSONAL DATA</h4>
      <p>We may share your Personal Data with Partner Companies to provide technical support or to provide specific services, such as hosting of the software, logistical software, maintenance services, database management or payment processing for purchases. Partner Companies will have access to your Personal Data only to perform these services on our behalf and are obligated not to disclose or use it for any other purpose.</p>
      <p>We may share some or all of your Personal Data with a parent company, any subsidiaries, joint ventures, or other companies under a common control (collectively, “Related Entities”), in which case we will require our Related Entities to honor this Privacy Policy.</p>
      <p>StowEdge LLC may sell/divest/transfer the company (including any shares in the company), or any combination of its products, services, assets and/or businesses. Personal Data may be among the items sold or otherwise transferred in these types of transactions. We may also sell, assign or otherwise transfer such information in the course of corporate divestitures, mergers, acquisitions, bankruptcies, dissolutions, reorganizations, liquidations, similar transactions or proceedings involving all or a portion of the company.</p>
      <p>Regardless of any choices you make regarding your Personal Data (if applicable), StowEdge LLC may disclose Personal Data if it believes in good faith that such disclosure is necessary to (a) comply with relevant laws or to respond to subpoenas or warrants served on StowEdge LLC; or (b) protect or defend the rights or property of StowEdge LLC or customers of the Services.</p>
      <p>Except as otherwise stated in this policy, we do not generally sell, trade, share, or rent the Personal Data collected from our services to third parties. You expressly consent to the sharing of your Personal Data as described in this policy.</p>
      <h4>CHOICE/OPT-OUT</h4>
      <p>StowEdge LLC offers you the choice of receiving different types of communication and information related to our company, products and services. You may elect to receive marketing communications and other special offers from us via email. If at any time you would like to change your communication preferences, we provide unsubscribe links and an opt-out mechanism for your convenience. You may also access and manage your preferences from your Account.</p>
      <h4>PERSONAL DATA CHANGES</h4>
      <p>You may change any of your Personal Data in your Account by editing your profile within the registration portion of the Site or by sending an email to us at the email address set forth below. You may request deletion of your Account information by us, but please note that we may be required (by law or otherwise) to keep this information and not delete it (or to keep this information for a certain time, in which case we will comply with your deletion request only after we have fulfilled such requirements).</p>
      <h4>CALIFORNIA PRIVACY RIGHTS</h4>
      <p>Customers who are California residents may request and obtain from us once a year, free of charge, certain information about the Personal Data (if any) we disclosed to third parties for direct marketing purposes in the preceding calendar year. If applicable, this information would include a list of the categories of Personal Data that was shared and the names and addresses of all third parties with which we shared information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to [___________________].</p>
      <h4>SECURITY OF YOUR PERSONAL DATA</h4>
      <p>StowEdge LLC is committed to protecting the security of your Personal Data. We use a variety of industry-standard security technologies and procedures to help protect your Personal Data from unauthorized access, use, or disclosure. We also require you to enter a password to access your Account information. Please do not disclose your Account password to unauthorized people. Despite these measures, you should know that StowEdge LLC cannot fully eliminate security risks associated with Personal Data.</p>
      <h4>STORAGE AND PROCESSING</h4>
      <p>Your information collected through the Services may be stored and processed in the United States or any other country in which StowEdge LLC or its affiliates or service providers maintain facilities. StowEdge LLC may transfer information that we collect about you, including Personal Data, to affiliated entities, or to other third parties across borders and from your country or jurisdiction to other countries or jurisdictions around the world. If you are located in the European Union, Switzerland or other regions with laws governing data collection and use that may differ from U.S. law, please note that we may transfer information, including Personal Data, to a country and jurisdiction that does not have the same data protection laws as your jurisdiction, and you consent to the transfer of information to the U.S. or any other country in which StowEdge LLC or its parent, subsidiaries, affiliates or service providers maintain facilities and the use and disclosure of information about you as described in this Privacy Policy.</p>
      <h4>CONTACT INFORMATION</h4>
      <p>StowEdge LLC welcomes your comments or questions regarding this Privacy Policy. Feel free to email comments or questions to us at [___________________].</p>
      <h4>CHANGES TO THIS PRIVACY POLICY</h4>
      <p>If StowEdge LLC makes changes to this Privacy Policy, these changes will be posted on the Site in a timely manner. StowEdge LLC reserves the right to modify this Privacy Policy at any time, so please review it frequently. You can determine when this Privacy Policy was last revised by referring to the "Last Updated" legend at the top of this page. Any changes to this Privacy Policy will become effective upon our posting of the revised Privacy Policy on the Site. Use of the Services following such changes constitutes your acceptance of the revised Privacy Policy then in effect.</p>
    </Grid>
  );
};

export default WebsiteTermsPage;
